# The purpose of this build is to validate that all solutions are kept up to date and compile.

pool:
  name: 'Azure Pipelines'
  demands: msbuild

variables:
  BuildServer: 'true'
  StableRelease: 'False'
  PublicRelease: 'True'

jobs:

- job: Everything.sln
  steps:
    - task: PowerShell@2
      displayName: 'PowerShell: Clean'
      inputs:
        targetType: filePath
        filePath: './.scripts/build_Clean.ps1'
        arguments: '-Directory $(AGENT.BUILDDIRECTORY) -CleanBinAndObj $True'
        errorActionPreference: silentlyContinue

    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet '

    - task: DotNetCoreCLI@2
      displayName: 'dotnet nuget locals all --clear'
      inputs:
        command: custom
        custom: nuget
        arguments: 'locals all --clear'
      enabled: false

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: Everything.sln
        feedsToUse: config
        nugetConfigPath: Nuget.config
        noCache: true
      continueOnError: true

    - task: MSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: Everything.sln
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/t:Restore;Build /p:BuildServer=$(BuildServer) /p:StableRelease=$(StableRelease) /p:PublicRelease=$(PublicRelease); /bl:"$(Build.StagingDirectory)\build.binlog"'
        clean: true


- job: ApplicationInsights.BaseSDKs.sln
  steps:
    - task: PowerShell@2
      displayName: 'PowerShell: Clean'
      inputs:
        targetType: filePath
        filePath: './.scripts/build_Clean.ps1'
        arguments: '-Directory $(AGENT.BUILDDIRECTORY) -CleanBinAndObj $True'
        errorActionPreference: silentlyContinue

    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet '

    - task: DotNetCoreCLI@2
      displayName: 'dotnet nuget locals all --clear'
      inputs:
        command: custom
        custom: nuget
        arguments: 'locals all --clear'
      enabled: false

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: ApplicationInsights.BaseSDKs.sln
        feedsToUse: config
        nugetConfigPath: Nuget.config
        noCache: true
      continueOnError: true

    - task: MSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: ApplicationInsights.BaseSDKs.sln
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/t:Restore;Build /p:BuildServer=$(BuildServer) /p:StableRelease=$(StableRelease) /p:PublicRelease=$(PublicRelease); /bl:"$(Build.StagingDirectory)\build.binlog"'
        clean: true

